### ISSUE TITLE
How to create users

### ISSUE THREAD

**Issue by Dokman** [ZhaobangChina/FtpServer#2]
So how i can create a user and where i can store it?

**Comment by taoyouh** [comment]
Are you using the library or the server app?

**Comment by Dokman** [comment]
The library i want to mánager users

**Comment by taoyouh** [comment]
If you are using the C# library, the SimpleAuthenticator class can be used to allow one user to log in. You can use it like this: 
```
var server = new FtpServer(
    localEP,
    new Zhaobang.FtpServer.File.SimpleFileProvider(baseDirectory),
    new Zhaobang.FtpServer.Connections.LocalDataConnectionFactory(),
    new Zhaobang.FtpServer.Authenticate.SimpleAuthenticator(userName, password)
);
```
If you want to add more than 1 users, you'll need to implement your own authenticator. Just write a class that implements interface Zhaobang.FtpServer.Authenticate.IAuthenticator and replace the SimpleAuthenticator above with your class. You can store your user info wherever you like.

**Comment by Dokman** [comment]
i think i will implement my own class because i want to use variuos users so it's more easy
