### ISSUE TITLE
FTPS Contribution

### ISSUE THREAD

**Issue by argenteneo-chrishope** [ZhaobangChina/FtpServer#3]
I would like contribute to this project. I have create a branch of your FTPS branch I would like to push but the repository permissions don't allow it.

**Comment by taoyouh** [comment]
Sorry for not noticing your issue.
To push to my repository, you need to fork my repo, work in the forked repo, and add a pull request in my repo. After doing that, I will be able to review your changes and finally merge them to my branch.

**Comment by taoyouh** [comment]
Do you have any further information or questions?

**Comment by taoyouh** [comment]
FTP over TLS is now on the master branch.
