### ISSUE TITLE
How to support virtual directories？

### ISSUE THREAD

**Issue by maikebing** [ZhaobangChina/FtpServer#5]

**Comment by taoyouh** [comment]
The CLI tool doesn't support virtual directories now. You can implement your own IFileProvider to handle the operations to support virtual directories.
PRs are welcomed.

**Comment by yuanrui** [comment]
The same question.
[FtpServer Issues How to support virtual directories？](https://github.com/FubarDevelopment/FtpServer/issues/80)

@taoyouh 一个人开发一个FtpServer 太耗费精力，后续维护得不偿失，另外对于.Net 社区的发展也是不利的。业内也有成熟的Ftp Server 方案[FileZilla Server](https://filezilla-project.org). 
.Net社区应该集中力量做一些成熟的项目，证明自己。朋友要是有兴趣话，可以去参与下这个项目的开发[FtpServer](https://github.com/FubarDevelopment/FtpServer)，这个项目从功能和架构上看，初步可以满足实际应用场景。但实际上还有很多问题没有解决，像性能、流量控制等方面还没有完善。
一点小小的建议，希望不要介意。

**Comment by taoyouh** [comment]
@yuanrui  FileZilla Server has nothing to do with .NET community. This project is not for file servers but for embedded use. FubarDevelopment/FtpServer did not support .NET Standard when this project started, and it does not support .NET Standard 1.4 today while this project does.
