### ISSUE TITLE
sftp on rasberry

### ISSUE THREAD

**Issue by schuttea** [ZhaobangChina/FtpServer#8]
Hello taoyouh,

I'm trying to connect with a sftp client on a rasberry pi.
The last command i get from it is this:

SSH-2.0-OpenSSH_7.9p1 Raspbian-10+deb10u2
and after that te server waits at the: 
var byteCount = await stream.ReadAsync(readByteBuffer, readOffset, readByteBuffer.Length - readOffset);

is the sftp client working with an different protocol?
this is my command:  sftp -oPort=21  anonymous@192.168.1.5

Filezilla on my local computer is working fine.

regards Barto

**Comment by taoyouh** [comment]
As far as I know, SFTP and FTP are two different protocols. You need an FTP client instead of an SFTP client.

**Comment by schuttea** [comment]
Ok thx.
